version: "3.8"

services:
  app:
    build: .
    ports:
      - "3000:3000"       # Map container port 3000 → host 3000
    depends_on:
      - mongo
    environment:
      - MONGO_URL=mongodb://mongo:27017/mydb
    volumes:
      - .:/app            # Mount current folder for live updates

  mongo:
    image: mongo:6
    restart: always
    ports:
      - "27017:27017"     # Optional: map MongoDB port
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
